[colors.bright]
black = "0x373b41"
blue = "0x1b68a9"
cyan = "0x29a0b9"
green = "0x3bc024"
magenta = "0xa039cd"
red = "0xbe0f24"
white = "0xc5c8c6"
yellow = "0xd5740a"

[colors.normal]
black = "0x282a2e"
blue = "0x319af1"
cyan = "0x47d6d6"
green = "0x78e13a"
magenta = "0xcc61fa"
red = "0xf51c45"
white = "0x707880"
yellow = "0xf3883e"

[colors.primary]
background = "0x040404"
foreground = "0xc5c8c6"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[window]
opacity = 0.5
title = "Terminal"

[window.padding]
x = 16
y = 16
